### ISSUE TITLE
Bundle seems to not work with Symfony 5.4

### ISSUE THREAD

**Issue by wehostadm** [kaistaerk/ajax-flash-message-bundle#1]
I have the error message : 
`Cannot access offset of type string on string`

in the file [vendor\kaistaerk\ajax-flash-message-bundle\Services\Messenger\Flash.php ](https://localhost:8000/_profiler/open?file=vendor\kaistaerk\ajax-flash-message-bundle\Services\Messenger\Flash.php&line=29#line29)(line 29)

How to fix it ?

**Comment by kaistaerkuandi** [comment]
How does your implementation looks like?
